### ISSUE TITLE
502 bad gateway error Nginx after upgrading to version 1.0.0

### ISSUE THREAD

**Issue by henrywright** [barisusakli/nodebb-plugin-imgur#11]
Since upgrading to version 1.0.0 (from 0.1.4) I'm unable to upload images. I get a 502 bad gateway error. Also, here's the error message I get when running `tail /var/log/nginx/error.log`

```
2015/08/13 17:32:03 [error] 26028#0: *446 upstream prematurely closed connection while reading response header from upstream, client: 92.24.92.254, server: example.com, request: "POST /api/post/upload HTTP/1.1", upstream: "http://127.0.1.1:4567/api/post/upload", host: "example.com", referrer: "https://example.com/topic/11/topic-name/9"
```

**Comment by barisusakli** [comment]
Whats in the nodebb logs? Also did you go tru the setup process detailed in the readme?

**Comment by henrywright** [comment]
Yes, I created a new Imgur app and went through the readme steps. What is the command to output the NodeBB logs? I'll copy them to here

**Comment by barisusakli** [comment]
`./nodebb log` in your nodebb directory then try to upload an image and see what happens. the file is in  logs/output.log

**Comment by henrywright** [comment]
Thanks, this is the entire NodeBB log output:

```
error: Unable to parse Imgur json response. [<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
] Unexpected token <
13/8 18:13 [26374] - error: [plugins] filter:uploadImage,  Unexpected token <
```

**Comment by barisusakli** [comment]
That usually means imgur is not responding. I just tested with 1.0.0 and it worked for me.

**Comment by henrywright** [comment]
Yes, it seems it wasn't responding when I tried to upload that first time. I just tried uploading a test image again and got this in the logs:
```
13/8 18:51 [26674] - error: TypeError: Cannot call method 'hasOwnProperty' of undefined
    at appendFormValue (/home/henrywright/nodebb/node_modules/request/request.js:340:17)
    at Request.init (/home/henrywright/nodebb/node_modules/request/request.js:354:11)
    at new Request (/home/henrywright/nodebb/node_modules/request/request.js:140:8)
    at request (/home/henrywright/nodebb/node_modules/request/index.js:55:10)
    at Function.post (/home/henrywright/nodebb/node_modules/request/index.js:63:12)
    at refreshToken (/home/henrywright/nodebb/node_modules/nodebb-plugin-imgur/index.js:87:11)
    at Request._callback (/home/henrywright/nodebb/node_modules/nodebb-plugin-imgur/index.js:189:13)
    at Request.self.callback (/home/henrywright/nodebb/node_modules/request/request.js:198:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/home/henrywright/nodebb/node_modules/request/request.js:1057:14)
TypeError: Cannot call method 'hasOwnProperty' of undefined
    at appendFormValue (/home/henrywright/nodebb/node_modules/request/request.js:340:17)
    at Request.init (/home/henrywright/nodebb/node_modules/request/request.js:354:11)
    at new Request (/home/henrywright/nodebb/node_modules/request/request.js:140:8)
    at request (/home/henrywright/nodebb/node_modules/request/index.js:55:10)
    at Function.post (/home/henrywright/nodebb/node_modules/request/index.js:63:12)
    at refreshToken (/home/henrywright/nodebb/node_modules/nodebb-plugin-imgur/index.js:87:11)
    at Request._callback (/home/henrywright/nodebb/node_modules/nodebb-plugin-imgur/index.js:189:13)
    at Request.self.callback (/home/henrywright/nodebb/node_modules/request/request.js:198:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/home/henrywright/nodebb/node_modules/request/request.js:1057:14)
```

**Comment by barisusakli** [comment]
Published 1.0.1 with better error messages give that one a try.

Also check your database for the key `nodebb-plugin-imgur` It should have access_token, refresh_token etc.

**Comment by henrywright** [comment]
Update: I just uninstalled 1.0.0 and installed 0.1.4 and the problem disappeared. I can now upload images again.

**Comment by henrywright** [comment]
Update 2: I noticed my Imgur secret doesn't seem to save in Installed Plugins > Imgur.

If I enter the client ID, then enter the secret, then click save and then navigate away from the page, when I go back to Installed Plugins > Imgur, the secret is missing from the text box.

**Comment by barisusakli** [comment]
That sounds like a cache issue, install 1.0.0 clear cache try again. 0.1.4 doesn't have a secret field

**Comment by henrywright** [comment]
> That sounds like a cache issue, install 1.0.0 clear cache try again. 0.1.4 doesn't have a secret field

I'm actually testing in 1.0.0 now. I just upgraded. Also just cleared my cache and the secret doesn't save. I think that could be the problem.

**Comment by barisusakli** [comment]
Give 1.0.2 a try.

**Comment by henrywright** [comment]
1.0.2 doesn't seem to be available in the NodeBB admin area. What's the recommended way to upgrade via the terminal?

**Comment by barisusakli** [comment]
`npm i nodebb-plugin-imgur` will do.

**Comment by henrywright** [comment]
Success! Many thanks for your help. Working perfectly now. No errors in the logs either.

**Comment by barisusakli** [comment]
No problem :)
