### ISSUE TITLE
Error on fresh install of 1.0.2

### ISSUE THREAD

**Issue by henrywright** [barisusakli/nodebb-plugin-imgur#12]
Hey guys,

When I do a fresh install of version 1.0.2 (not an upgrade) I get this error message when I visit Installed Plugins > Imgur:

```
Internal error.
Oops! Looks like something went wrong!
/api/admin/plugins/imgur
Cannot read property 'imgurClientID' of null
```

**Comment by barisusakli** [comment]
Can you check the nodebb logs for any errors?

**Comment by henrywright** [comment]
Sure. I see this in the NodeBB logs:
```
14/8 23:39 [10985] - [31merror[39m: /api/admin/plugins/imgur
 TypeError: Cannot read property 'imgurClientID' of null
    at renderAdmin (/nodebb/node_modules/nodebb-plugin-imgur/index.js:36:27)
    at Layer.handle [as handle_request] (/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at next (/nodebb/node_modules/express/lib/router/route.js:131:13)
    at csrf (/nodebb/node_modules/csurf/index.js:100:5)
    at Layer.handle [as handle_request] (/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at next (/nodebb/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/nodebb/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at /nodebb/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/nodebb/node_modules/express/lib/router/index.js:330:12)
```

**Comment by barisusakli** [comment]
Try with 1.0.3

**Comment by henrywright** [comment]
1.0.3 fixed the error. Many thanks again for your help!
