### ISSUE TITLE
NodeBB Crash when Upload image

### ISSUE THREAD

**Issue by AndreasKnight** [barisusakli/nodebb-plugin-imgur#16]
```
30/8 17:28 [16428] - info: NodeBB is now listening on: 0.0.0.0:4567
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ReadStream.EventEmitter.addListener (events.js:160:15)
    at Function.DelayedStream.create (/root/NBB/node_modules/request/node_modules/combined-stream/node_modules/delayed-stream/lib/delayed_stream.js:33:10)
    at FormData.CombinedStream.append (/root/NBB/node_modules/request/node_modules/combined-stream/lib/combined_stream.js:43:37)
    at FormData.append (/root/NBB/node_modules/request/node_modules/form-data/lib/form_data.js:46:3)
    at appendFormValue (/root/NBB/node_modules/request/request.js:343:21)
    at Request.init (/root/NBB/node_modules/request/request.js:354:11)
    at new Request (/root/NBB/node_modules/request/request.js:140:8)
    at request (/root/NBB/node_modules/request/index.js:55:10)
    at Function.post (/root/NBB/node_modules/request/index.js:63:12)
    at doUpload (/root/NBB/node_modules/nodebb-plugin-imgur/index.js:183:12)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ReadStream.EventEmitter.addListener (events.js:160:15)
    at FormData.CombinedStream.append (/root/NBB/node_modules/request/node_modules/combined-stream/lib/combined_stream.js:47:14)
    at FormData.append (/root/NBB/node_modules/request/node_modules/form-data/lib/form_data.js:46:3)
    at appendFormValue (/root/NBB/node_modules/request/request.js:343:21)
    at Request.init (/root/NBB/node_modules/request/request.js:354:11)
    at new Request (/root/NBB/node_modules/request/request.js:140:8)
    at request (/root/NBB/node_modules/request/index.js:55:10)
    at Function.post (/root/NBB/node_modules/request/index.js:63:12)
    at doUpload (/root/NBB/node_modules/nodebb-plugin-imgur/index.js:183:12)
    at uploadToImgur (/root/NBB/node_modules/nodebb-plugin-imgur/index.js:210:4)
30/8 17:31 [16428] - error: undefined
undefined
30/8 17:31 [16428] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
30/8 17:31 [16428] - info: [app] Database connection closed.
30/8 17:31 [16428] - info: [app] Web server closed to connections.
30/8 17:31 [16428] - info: [app] Shutdown complete.
[cluster] Child Process (16428) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
30/8 17:31 [16468] - info: Time: Sun Aug 30 2015 17:31:12 GMT-0400 (EDT)
30/8 17:31 [16468] - info: Initializing NodeBB v0.8.0
Warning: Redis server does not require a password, but a password was supplied.
Warning: Redis server does not require a password, but a password was supplied.
Warning: Redis server does not require a password, but a password was supplied.
Warning: Redis server does not require a password, but a password was supplied.
Warning: Redis server does not require a password, but a password was supplied.

30/8 17:31 [16468] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-plugin-emailer-mandrill
  * nodebb-plugin-emoji-extended
  * nodebb-plugin-spam-be-gone
  * nodebb-plugin-desktop-notifications
  * nodebb-plugin-youtube

30/8 17:31 [16468] - info: [plugins/spam-be-gone] Settings loaded
30/8 17:31 [16468] - info: NodeBB Ready
30/8 17:31 [16468] - info: Enabling 'trust proxy'
30/8 17:31 [16468] - info: NodeBB is now listening on: 0.0.0.0:4567
```

Fix?

**Comment by martyalicante** [comment]
confirmed, on 0.7.x

**Comment by AndreasKnight** [comment]
fixxed
