### ISSUE TITLE
Update to 1.1.0 Now Gets Parsing Errors

### ISSUE THREAD

**Issue by scottalanmiller** [barisusakli/nodebb-plugin-imgur#35]
Updated to 1.0.2 (with 1.10.2) and now no uploads work, we get to 100% and get a parsing error every time.  Then it says that the community has disconnected.

If you log into https://mangolassi.it/ and try to upload an image, you can see it happen consistently.

**Comment by sorvani** [comment]
This also happens on my board https://obelisk.daerma.com

**Comment by sorvani** [comment]
Here is a screenshot of the error from my community.
![image](https://user-images.githubusercontent.com/3302372/47318434-acff4a00-d611-11e8-9bcf-e65087da0776.png)

**Comment by sorvani** [comment]
I did notice the plugin page shows this
`Register an imgur app here, make sure you fill in the callback URL properly. It should be http://yourforum.com/admin/plugins/imgur adjust based on your forum url. `

but in my imgur account it was `https://yourforum.com/admin/plugins/imgur/oath` I just updated it to remove the `oath`. Will report back after the imgur update period (15ish minutes).

**Comment by barisusakli** [comment]
The latest version of this plugin is 1.1.0 I tested an upload and it works at https://community.nodebb.org/topic/12975/mastodon-iframely-embed-test.

Which version of the plugin are you using?

**Comment by scottalanmiller** [comment]
1.0.2, that is still showing as of one minute ago, as the latest version in NodeBB 1.10.2.  It is the version that it updated to as part of the update process, and no newer version is showing.

**Comment by sorvani** [comment]
I think @scottalanmiller did the same thing I did and looked and the imgbed version.
My imgur plugin is also 1.1.0
![e2b9c4d2-9906-43bc-8cbd-5f69c97c80e6](https://user-images.githubusercontent.com/3302372/47329987-45122900-d63c-11e8-89c3-183ab860d408.png)

**Comment by scottalanmiller** [comment]
I did

**Comment by barisusakli** [comment]
Can you guys post the messages you get in `logs/output.log` when you try to upload something and get the error?

**Comment by sorvani** [comment]
Sorry, was not able to do that until now.
Here you go. I stopped my board, rebuilt assets and started it again to make sure it was a clean start.

It is totally crashing the process and the system is starting a new one.
```
[root@daermabb ~]# tail -f /opt/daerma/nodebb/logs/output.log 
[cluster] Spinning up another process...
2018-10-22T21:20:37.660Z [3871] - info: Initializing NodeBB v1.10.2 http://obelisk.daerma.com
[benchpressjs] Unable to build or find a suitable native module, falling back to JS version
2018-10-22T21:20:40.559Z [3871] - info: [socket.io] Restricting access to origin: http://obelisk.daerma.com:*
info: Imgbed: regex recompiled: (?<url>https?:\/\/[^\s]+\/(?<filename>[\w_0-9\-\.]+\.(jpg|jpeg|gif|gifv|png|svg))([^\s]*)?)
info: Imgbed: cache initialized to size 3
2018-10-22T21:20:41.664Z [3871] - info: Routes added
2018-10-22T21:20:41.667Z [3871] - info: NodeBB Ready
2018-10-22T21:20:41.671Z [3871] - info: Enabling 'trust proxy'
2018-10-22T21:20:41.678Z [3871] - info: NodeBB is now listening on: 0.0.0.0:4567
2018-10-23T20:00:58.762Z [3871] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2018-10-23T20:00:58.767Z [3871] - info: [app] Web server closed to connections.
2018-10-23T20:00:58.769Z [3871] - info: [app] Database connection closed.
2018-10-23T20:00:58.769Z [3871] - info: [app] Shutdown complete.
[cluster] Child Process (3871) has exited (code: 0, signal: null)

NodeBB v1.10.2 Copyright (C) 2013-2014 NodeBB Inc.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions.
For the full license, please visit: http://www.gnu.org/copyleft/gpl.html

Clustering enabled: Spinning up 1 process(es).

2018-10-23T20:03:05.219Z [6803] - info: Initializing NodeBB v1.10.2 http://obelisk.daerma.com
[benchpressjs] Unable to build or find a suitable native module, falling back to JS version
2018-10-23T20:03:20.814Z [6803] - info: [socket.io] Restricting access to origin: http://obelisk.daerma.com:*
info: Imgbed: regex recompiled: (?<url>https?:\/\/[^\s]+\/(?<filename>[\w_0-9\-\.]+\.(jpg|jpeg|gif|gifv|png|svg))([^\s]*)?)
info: Imgbed: cache initialized to size 3
2018-10-23T20:03:26.061Z [6803] - info: Routes added
2018-10-23T20:03:26.064Z [6803] - info: NodeBB Ready
2018-10-23T20:03:26.068Z [6803] - info: Enabling 'trust proxy'
2018-10-23T20:03:26.075Z [6803] - info: NodeBB is now listening on: 0.0.0.0:4567
2018-10-23T20:04:23.171Z [6803] - error:  Error: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /opt/daerma/nodebb/node_modules/sharp/build/Release/../../vendor/lib/libpng16.so.16)
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/daerma/nodebb/node_modules/sharp/lib/constructor.js:10:15)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/daerma/nodebb/node_modules/sharp/lib/index.js:3:15)
2018-10-23T20:04:23.173Z [6803] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2018-10-23T20:04:23.177Z [6803] - info: [app] Web server closed to connections.
2018-10-23T20:04:23.182Z [6803] - info: [app] Database connection closed.
2018-10-23T20:04:23.182Z [6803] - info: [app] Shutdown complete.
[cluster] Child Process (6803) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
2018-10-23T20:04:23.658Z [6815] - info: Initializing NodeBB v1.10.2 http://obelisk.daerma.com
[benchpressjs] Unable to build or find a suitable native module, falling back to JS version
2018-10-23T20:04:26.565Z [6815] - info: [socket.io] Restricting access to origin: http://obelisk.daerma.com:*
info: Imgbed: regex recompiled: (?<url>https?:\/\/[^\s]+\/(?<filename>[\w_0-9\-\.]+\.(jpg|jpeg|gif|gifv|png|svg))([^\s]*)?)
info: Imgbed: cache initialized to size 3
2018-10-23T20:04:27.601Z [6815] - info: Routes added
2018-10-23T20:04:27.604Z [6815] - info: NodeBB Ready
2018-10-23T20:04:27.608Z [6815] - info: Enabling 'trust proxy'
2018-10-23T20:04:27.613Z [6815] - info: NodeBB is now listening on: 0.0.0.0:4567
```

Here is just the error.
```
2018-10-23T20:04:23.171Z [6803] - error:  Error: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /opt/daerma/nodebb/node_modules/sharp/build/Release/../../vendor/lib/libpng16.so.16)
```

My system is running on CentOS 7 and ZLIB is 1.2.7
![image](https://user-images.githubusercontent.com/3302372/47387659-9de1d000-d6d5-11e8-9ea2-0851f8337f63.png)

**Comment by scottalanmiller** [comment]
Same here, CentOS 7, ZLIB 1.2.7, NodeJS 6.14.3

2018-10-23T20:26:52.332Z [1485] - error:  Error: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /opt/mangolassi-1.0/node_modules/sharp/build/Release/../../vendor/lib/libpng16.so.16)
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/mangolassi-1.0/node_modules/sharp/lib/constructor.js:10:15)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/mangolassi-1.0/node_modules/sharp/lib/index.js:3:15)
2018-10-23T20:26:52.334Z [1485] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2018-10-23T20:26:52.491Z [1485] - info: [app] Web server closed to connections.
2018-10-23T20:26:52.497Z [1485] - info: [app] Database connection closed.
2018-10-23T20:26:52.498Z [1485] - info: [app] Shutdown complete.
[cluster] Child Process (1485) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
2018-10-23T20:26:53.003Z [8044] - info: Initializing NodeBB v1.10.2 https://mangolassi.it
[benchpressjs] Unable to build or find a suitable native module, falling back to JS version
2018-10-23T20:26:55.739Z [8044] - warn: [upgrade/appendPluginScripts] Unable to read plugin.json for plugin `nodebb-plugin-dwnvtr`. Skipping.
2018-10-23T20:26:55.740Z [8044] - warn: [upgrade/appendPluginScripts] Unable to read plugin.json for plugin `nodebb-plugin-color`. Skipping.
2018-10-23T20:26:55.740Z [8044] - warn: [upgrade/appendPluginScripts] Unable to read plugin.json for plugin `nodebb-plugin-outside`. Skipping.
2018-10-23T20:26:55.740Z [8044] - warn: [upgrade/appendPluginScripts] Unable to read plugin.json for plugin `nodebb-plugin-category-info`. Skipping.
2018-10-23T20:26:55.740Z [8044] - warn: [upgrade/appendPluginScripts] Unable to read plugin.json for plugin `nodebb-plugin-designer`. Skipping.
2018-10-23T20:26:55.741Z [8044] - warn: [upgrade/appendPluginScripts] Unable to read plugin.json for plugin `nodebb-plugin-finder`. Skipping.
2018-10-23T20:26:56.431Z [8044] - info: [socket.io] Restricting access to origin: *:*
info: EmbedGMap settings loaded
info: Imgbed: regex recompiled: (?<url>https?:\/\/[^\s]+\/(?<filename>[\w_0-9\-\.]+\.(jpg|jpeg|gif|gifv|png|svg))([^\s]*)?)
info: Imgbed: cache initialized to size 3
info: EmbedGMap API Key: 
2018-10-23T20:26:57.652Z [8044] - info: [plugins/spam-be-gone] Settings loaded
....

**Comment by sorvani** [comment]
So, running on the assumption that this is actually a nodejs issue, I switched back to v10.8.0 (down from v10.12.0) and rebuilt everything. and it works again.
![image](https://user-images.githubusercontent.com/3302372/47388911-05e5e580-d6d9-11e8-8814-b9c56a81b5d1.png)
![image](https://user-images.githubusercontent.com/3302372/47388936-14340180-d6d9-11e8-8c64-169c4e72073a.png)
everything works.
![image](https://user-images.githubusercontent.com/3302372/47388979-2877fe80-d6d9-11e8-8d35-a489e8324787.png)

**Comment by barisusakli** [comment]
This issue isn't related to the imgur plugin at all, it seems to be an issue with the OS and image library we are using https://github.com/lovell/sharp.

@sorvani are you saying everything works fine on node 10.8.0 and crashes on 10.12.0? Or does it crash on both versions?

I am not sure why sharp is looking for zlib1.2.9 when the system has 1.2.7 maybe you guys can report this at https://github.com/lovell/sharp/issues and post  the same info above.

**Comment by sorvani** [comment]
@barisusakli yes, it works fine on node 10.8.0 and crashes on 10.12.0 Once I saw that, I agree that it likely was not your specific issue in the plugin itself.
